baseurl: https://GAOYUEtianc.github.io/blogs/
languageCode: en
title: Anna's Web
theme: soho
summarylength: 7
# paginate: 7

enableEmoji: true
enableRobotsTXT: true
smartypants: false



mathjax: true

googleAnalytics: UA-55543164-1
# disqusShortname:

params:
  author: Gao Yue (Anna)
  # themeColor: "#FF8C00"
  # description: Anna's Webpage
  gravatar: gao12@ualberta.ca

  copyright: Gao Yue
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0

  socialIcons:
    - icon: fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/yue-anna-gao-49a834107/
    - icon: fa-github
      title: GitHub
      url: https://github.com/GAOYUEtianc
    - icon: fa-facebook
      title: Facebook
      url: https://www.facebook.com/yue.gao.925
    

  customCss:
    - 'css/blog.css'

  # customJs:
  #   - '#'

menu:
  main:
  - name: Posts
    weight: 100
    identifier: posts
    url: /posts/
  - name: About Me
    identifier: about
    weight: 300
    url: /about/
 

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
